import React, { createContext, useContext, useState } from "react";

type Language = "en" | "hi" | "ja" | "fr" | "ru" | "es" | "de" | "ar" | "zh" | "it";

interface LanguageContextType {
  lang: Language;
  setLang: (l: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Header
    "header.tagline": "Powered by Government of India Tourism Initiative",
    "header.lang_en": "EN",
    "header.lang_hi": "हिंदी",
    "header.tourist_login": "Tourist Login",

    // Hero
    "hero.title": "Your Safety is Our Priority",
    "hero.subtitle":
      "Welcome to India! We are committed to making your journey safe & memorable. Register your yourself and explore with confidence and safety.",
    "hero.badge1": " Encrypted Details",
    "hero.badge2": " 24/7 Support",
    "hero.badge3": " Official Authority Access",

    // Traveler Portal
    "traveler.heading": "Register Your Travel",
    "traveler.subheading":
      "Register yourself here and let us know your journey",
    "traveler.name": "Full Name",
    "traveler.passport": "Passport Number",
    "traveler.phone": "Phone Number",
    "traveler.city": "Current City",
    "traveler.nationality": "Nationality",
    "traveler.name_placeholder": "e.g. John Smith",
    "traveler.passport_placeholder": "e.g. A12345678",
    "traveler.phone_placeholder": "+91 9876878595",
    "traveler.city_placeholder": "e.g. New Delhi",
    "traveler.nationality_placeholder": "e.g. United Kingdom",
    "traveler.submit": "Submit Registration",
    "traveler.submitted": "Registration Submitted!",

    // Authority Portal
    "authority.badge": "Departmental Access Only",
    "authority.heading": "Police / Authority Access",
    "authority.subheading":
      "Secure portal for verified government officials only.",
    "authority.officer_id": "Officer ID",
    "authority.password": "Password",
    "authority.officer_id_placeholder": "Enter your ID",
    "authority.password_placeholder": "Enter your password",
    "authority.login": "Secure Login",
    "authority.note": "Unauthorized access is a punishable offence.",

    // Safety Guide
    "safety.section_title": "Your Safety Companion along your trip",
    "safety.section_sub": "Stay Safe in India With Us",
    "safety.emergency_title": "National Emergency",
    "safety.emergency_num": "112",
    "safety.emergency_desc": "Dial 112 for any help police, fire, or ambulance available 24/7 across India.",
    "safety.medical_title": "Medical Help",
    "safety.medical_num": "108",
    "safety.medical_desc": "108 Ambulance Services free emergency medical response.",
    "safety.police_title": "Tourist Police",
    "safety.police_num": "1800-111-363",
    "safety.police_desc": "Toll-free helpline dedicated to tourist assistance and safety.",
    "safety.rights_title": "Know Your Rights",
    "safety.rights_desc":
      "As a tourist you have the right to police assistance, fair pricing, and emergency access to all goods.",
    "safety.tips_title": "Safe Travel Tips",
    "safety.tips_desc": "Follow the 5 Golden Rules for a safe and comfortable journey across India.",
    "safety.report_title": "Report an Incident",
    "safety.report_desc": "Experienced a problem? Report it instantly and get help from authorities.",
    "safety.report_btn": "Report Now",

    // Golden Rules
    "rules.title": "5 Golden Rules",
    "rules.subtitle": "for a Safe Journey in India",
    "rules.1_title": "Keep Passport Copies",
    "rules.1_desc": "Always carry digital and physical copies of your passport and visa documents.",
    "rules.2_title": "Share Your Itinerary",
    "rules.2_desc": "Tell someone you trust your travel plan, hotel details, and daily schedule.",
    "rules.3_title": "Use Official Transport",
    "rules.3_desc": "Only use licenced taxis, OLA/UBERS, or book tickets via IRCTC or through any registered apps.",
    "rules.4_title": "Save Numbers Offline or on device",
    "rules.4_desc": "Store emergency contacts 112, 108, Hotel, Family & Tourist Police offline on your device.",
    "rules.5_title": "Register Every City",
    "rules.5_desc": "This portal will keep a track of your location to keep you safe from high risk area.",

    // Report Modal
    "modal.title": "Report an Incident",
    "modal.name": "Your Name as per passport",
    "modal.incident_type": "Incident Type",
    "modal.location": "Location",
    "modal.description": "Description",
    "modal.submit": "Submit Report",
    "modal.cancel": "Cancel",
    "modal.submitted": "Report Submitted!",

    // Footer
    "footer.mission": "Dedicated to making India the safest and most welcoming destination for every traveller.",
    "footer.links_title": "Quick Links",
    "footer.home": "Home",
    "footer.safety": "Safety Guide",
    "footer.emergency": "Emergency Contacts",
    "footer.about": "About",
    "footer.ministry": "Ministry of Tourism, Government of India",
    "footer.rights": "2024 Trust Tour. All rights reserved.",
  },
  hi: {
    // Header
    "header.tagline": "भारत सरकार की पर्यटन पहल द्वारा संचालित",
    "header.lang_en": "EN",
    "header.lang_hi": "हिंदी",
    "header.tourist_login": "पर्यटक लॉगिन",

    // Hero
    "hero.title": "आपकी सुरक्षा हमारी प्राथमिकता है",
    "hero.subtitle":
      "भारत में आपका स्वागत है! हम आपकी यात्रा को सुरक्षित और यादगार बनाने के लिए प्रतिबद्ध हैं। अपना पंजीकरण करें और आत्मविश्वास और सुरक्षा के साथ पर्यटन का आनंद लें।",
    "hero.badge1": " एन्क्रिप्टेड विवरण",
    "hero.badge2": " 24/7 सहायता",
    "hero.badge3": " आधिकारिक प्राधिकरण पहुँच",

    // Traveler Portal
    "traveler.heading": "अपनी यात्रा पंजीकृत करें",
    "traveler.subheading":
      "यहां अपना पंजीकरण करें और हमें अपनी यात्रा के बारे में बताएं",
    "traveler.name": "पूरा नाम",
    "traveler.passport": "पासपोर्ट नंबर",
    "traveler.phone": "फ़ोन नंबर",
    "traveler.city": "वर्तमान शहर",
    "traveler.nationality": "राष्ट्रीयता",
    "traveler.name_placeholder": "उदा. जॉन स्मिथ",
    "traveler.passport_placeholder": "उदा. A12345678",
    "traveler.phone_placeholder": "+91 9876878595",
    "traveler.city_placeholder": "उदा. नई दिल्ली",
    "traveler.nationality_placeholder": "उदा. यूनाइटेड किंगडम",
    "traveler.submit": "पंजीकरण जमा करें",
    "traveler.submitted": "पंजीकरण जमा कर दिया गया!",

    // Authority Portal
    "authority.badge": "केवल विभागीय पहुंच",
    "authority.heading": "पुलिस / प्राधिकरण पहुंच",
    "authority.subheading":
      "केवल सत्यापित सरकारी अधिकारियों के लिए सुरक्षित पोर्टल।",
    "authority.officer_id": "अधिकारी आईडी",
    "authority.password": "पासवर्ड",
    "authority.officer_id_placeholder": "अपनी आईडी दर्ज करें",
    "authority.password_placeholder": "अपना पासवर्ड दर्ज करें",
    "authority.login": "सुरक्षित लॉगिन",
    "authority.note": "अनाधिकृत पहुंच एक दंडनीय अपराध है।",

    // Safety Guide
    "safety.section_title": "आपकी यात्रा के दौरान आपका सुरक्षा साथी",
    "safety.section_sub": "हमारे साथ भारत में सुरक्षित रहें",
    "safety.emergency_title": "राष्ट्रीय आपातकाल",
    "safety.emergency_num": "112",
    "safety.emergency_desc": "पुलिस, फायर, या एम्बुलेंस की किसी भी सहायता के लिए 112 डायल करें, जो पूरे भारत में 24/7 उपलब्ध है।",
    "safety.medical_title": "चिकित्सा सहायता",
    "safety.medical_num": "108",
    "safety.medical_desc": "108 एम्बुलेंस सेवाएं निःशुल्क आपातकालीन चिकित्सा प्रतिक्रिया।",
    "safety.police_title": "पर्यटक पुलिस",
    "safety.police_num": "1800-111-363",
    "safety.police_desc": "पर्यटक सहायता और सुरक्षा को समर्पित टोल-फ्री हेल्पलाइन।",
    "safety.rights_title": "अपने अधिकार जानें",
    "safety.rights_desc":
      "एक पर्यटक के रूप में आपको पुलिस सहायता, उचित मूल्य निर्धारण और सभी वस्तुओं तक आपातकालीन पहुंच का अधिकार है।",
    "safety.tips_title": "सुरक्षित यात्रा युक्तियाँ",
    "safety.tips_desc": "भारत भर में सुरक्षित और आरामदायक यात्रा के लिए 5 सुनहरे नियमों का पालन करें।",
    "safety.report_title": "किसी घटना की रिपोर्ट करें",
    "safety.report_desc": "कोई समस्या आई? तुरंत इसकी रिपोर्ट करें और अधिकारियों से मदद पाएं।",
    "safety.report_btn": "अभी रिपोर्ट करें",

    // Golden Rules
    "rules.title": "5 सुनहरे नियम",
    "rules.subtitle": "भारत में सुरक्षित यात्रा के लिए",
    "rules.1_title": "पासपोर्ट की प्रतियां रखें",
    "rules.1_desc": "हमेशा अपने पासपोर्ट और वीज़ा दस्तावेजों की डिजिटल और भौतिक प्रतियां साथ रखें।",
    "rules.2_title": "अपनी यात्रा कार्यक्रम साझा करें",
    "rules.2_desc": "जिस पर आप भरोसा करते हैं, उसे अपनी यात्रा योजना, होटल का विवरण और दैनिक कार्यक्रम बताएं।",
    "rules.3_title": "आधिकारिक परिवहन का उपयोग करें",
    "rules.3_desc": "केवल लाइसेंस प्राप्त टैक्सियों, ओला/उबर का उपयोग करें, या आईआरसीटीसी या किसी भी पंजीकृत ऐप के माध्यम से टिकट बुक करें।",
    "rules.4_title": "नंबर ऑफ़लाइन या डिवाइस पर सहेजें",
    "rules.4_desc": "आपातकालीन संपर्क 112, 108, होटल, परिवार और पर्यटक पुलिस को अपने डिवाइस पर ऑफ़लाइन सहेजें।",
    "rules.5_title": "हर शहर को पंजीकृत करें",
    "rules.5_desc": "यह पोर्टल आपको उच्च जोखिम वाले क्षेत्र से सुरक्षित रखने के लिए आपके स्थान का ट्रैक रखेगा।",

    // Report Modal
    "modal.title": "किसी घटना की रिपोर्ट करें",
    "modal.name": "पासपोर्ट के अनुसार आपका नाम",
    "modal.incident_type": "घटना का प्रकार",
    "modal.location": "स्थान",
    "modal.description": "विवरण",
    "modal.submit": "रिपोर्ट जमा करें",
    "modal.cancel": "रद्द करें",
    "modal.submitted": "रिपोर्ट जमा हो गई!",

    // Footer
    "footer.mission": "भारत को प्रत्येक यात्री के लिए सबसे सुरक्षित और सबसे स्वागत योग्य गंतव्य बनाने के लिए समर्पित।",
    "footer.links_title": "त्वरित लिंक",
    "footer.home": "होम",
    "footer.safety": "सुरक्षा गाइड",
    "footer.emergency": "आपातकालीन संपर्क",
    "footer.about": "हमारे बारे में",
    "footer.ministry": "पर्यटन मंत्रालय, भारत सरकार",
    "footer.rights": "2024 ट्रस्ट टूर। सर्वाधिकार सुरक्षित।",
  },
  ja: {
    // Japanese translations (Mock/English fallback for brevity)
    "header.tagline": "インド政府観光局イニシアチブ提供",
    "header.lang_en": "EN",
    "header.lang_hi": "हिंदी",
    "header.tourist_login": "旅行者ログイン",
    "hero.title": "お客様の安全を第一に考えています",
    "hero.subtitle": "インドへようこそ！安全で思い出に残るご旅行をお約束いたします。",
    "hero.badge1": "暗号化された詳細情報",
    "hero.badge2": "24時間365日のサポート",
    "hero.badge3": "公式アクセス",
    "traveler.heading": "ご旅行の登録",
    "traveler.subheading": "ご旅行についてお知らせください",
    "traveler.name": "氏名",
    "traveler.passport": "パスポート番号",
    "traveler.phone": "電話番号",
    "traveler.city": "現在の都市",
    "traveler.nationality": "国籍",
    "traveler.name_placeholder": "例: John Smith",
    "traveler.passport_placeholder": "例: A12345678",
    "traveler.phone_placeholder": "+91 9876878595",
    "traveler.city_placeholder": "例: ニューデリー",
    "traveler.nationality_placeholder": "例: イギリス",
    "traveler.submit": "登録を送信",
    "traveler.submitted": "登録が完了しました！",
    // Adding fallbacks for the rest of the object
    "authority.badge": "Departmental Access Only",
    "authority.heading": "Police / Authority Access",
    "authority.subheading": "Secure portal for verified government officials only.",
    "authority.officer_id": "Officer ID",
    "authority.password": "Password",
    "authority.officer_id_placeholder": "Enter your ID",
    "authority.password_placeholder": "Enter your password",
    "authority.login": "Secure Login",
    "authority.note": "Unauthorized access is a punishable offence.",
    "safety.section_title": "Your Safety Companion along your trip",
    "safety.section_sub": "Stay Safe in India With Us",
    "safety.emergency_title": "National Emergency",
    "safety.emergency_num": "112",
    "safety.emergency_desc": "Dial 112 for any help police, fire, or ambulance available 24/7 across India.",
    "safety.medical_title": "Medical Help",
    "safety.medical_num": "108",
    "safety.medical_desc": "108 Ambulance Services free emergency medical response.",
    "safety.police_title": "Tourist Police",
    "safety.police_num": "1800-111-363",
    "safety.police_desc": "Toll-free helpline dedicated to tourist assistance and safety.",
    "safety.rights_title": "Know Your Rights",
    "safety.rights_desc": "As a tourist you have the right to police assistance, fair pricing, and emergency access to all goods.",
    "safety.tips_title": "Safe Travel Tips",
    "safety.tips_desc": "Follow the 5 Golden Rules for a safe and comfortable journey across India.",
    "safety.report_title": "Report an Incident",
    "safety.report_desc": "Experienced a problem? Report it instantly and get help from authorities.",
    "safety.report_btn": "Report Now",
    "rules.title": "5 Golden Rules",
    "rules.subtitle": "for a Safe Journey in India",
    "rules.1_title": "Keep Passport Copies",
    "rules.1_desc": "Always carry digital and physical copies of your passport and visa documents.",
    "rules.2_title": "Share Your Itinerary",
    "rules.2_desc": "Tell someone you trust your travel plan, hotel details, and daily schedule.",
    "rules.3_title": "Use Official Transport",
    "rules.3_desc": "Only use licenced taxis, OLA/UBERS, or book tickets via IRCTC or through any registered apps.",
    "rules.4_title": "Save Numbers Offline or on device",
    "rules.4_desc": "Store emergency contacts 112, 108, Hotel, Family & Tourist Police offline on your device.",
    "rules.5_title": "Register Every City",
    "rules.5_desc": "This portal will keep a track of your location to keep you safe from high risk area.",
    "modal.title": "Report an Incident",
    "modal.name": "Your Name as per passport",
    "modal.incident_type": "Incident Type",
    "modal.location": "Location",
    "modal.description": "Description",
    "modal.submit": "Submit Report",
    "modal.cancel": "Cancel",
    "modal.submitted": "Report Submitted!",
    "footer.mission": "Dedicated to making India the safest and most welcoming destination for every traveller.",
    "footer.links_title": "Quick Links",
    "footer.home": "Home",
    "footer.safety": "Safety Guide",
    "footer.emergency": "Emergency Contacts",
    "footer.about": "About",
    "footer.ministry": "Ministry of Tourism, Government of India",
    "footer.rights": "2024 Trust Tour. All rights reserved.",
  },
  fr: {
    // French translation
    "header.tagline": "Propulsé par l'Initiative du Gouvernement Indien",
    "header.lang_en": "EN",
    "header.lang_hi": "हिंदी",
    "header.tourist_login": "Connexion Touriste",
    "hero.title": "Votre Sécurité est Notre Priorité",
    "hero.subtitle": "Bienvenue en Inde ! Nous nous engageons à rendre votre voyage sûr et mémorable.",
    "hero.badge1": "Détails Cryptés",
    "hero.badge2": "Assistance 24/7",
    "hero.badge3": "Accès Officiel",
    "traveler.heading": "Enregistrez Votre Voyage",
    "traveler.subheading": "Dites-nous votre parcours",
    "traveler.name": "Nom Complet",
    "traveler.passport": "Numéro de Passeport",
    "traveler.phone": "Numéro de Téléphone",
    "traveler.city": "Ville Actuelle",
    "traveler.nationality": "Nationalité",
    "traveler.name_placeholder": "ex. John Smith",
    "traveler.passport_placeholder": "ex. A12345678",
    "traveler.phone_placeholder": "+91 9876878595",
    "traveler.city_placeholder": "ex. New Delhi",
    "traveler.nationality_placeholder": "ex. Royaume-Uni",
    "traveler.submit": "Soumettre",
    "traveler.submitted": "Enregistrement Soumis !",
    "authority.badge": "Departmental Access Only",
    "authority.heading": "Police / Authority Access",
    "authority.subheading": "Secure portal for verified government officials only.",
    "authority.officer_id": "Officer ID",
    "authority.password": "Password",
    "authority.officer_id_placeholder": "Enter your ID",
    "authority.password_placeholder": "Enter your password",
    "authority.login": "Secure Login",
    "authority.note": "Unauthorized access is a punishable offence.",
    "safety.section_title": "Your Safety Companion along your trip",
    "safety.section_sub": "Stay Safe in India With Us",
    "safety.emergency_title": "National Emergency",
    "safety.emergency_num": "112",
    "safety.emergency_desc": "Dial 112 for any help police, fire, or ambulance available 24/7 across India.",
    "safety.medical_title": "Medical Help",
    "safety.medical_num": "108",
    "safety.medical_desc": "108 Ambulance Services free emergency medical response.",
    "safety.police_title": "Tourist Police",
    "safety.police_num": "1800-111-363",
    "safety.police_desc": "Toll-free helpline dedicated to tourist assistance and safety.",
    "safety.rights_title": "Know Your Rights",
    "safety.rights_desc": "As a tourist you have the right to police assistance, fair pricing, and emergency access to all goods.",
    "safety.tips_title": "Safe Travel Tips",
    "safety.tips_desc": "Follow the 5 Golden Rules for a safe and comfortable journey across India.",
    "safety.report_title": "Report an Incident",
    "safety.report_desc": "Experienced a problem? Report it instantly and get help from authorities.",
    "safety.report_btn": "Report Now",
    "rules.title": "5 Golden Rules",
    "rules.subtitle": "for a Safe Journey in India",
    "rules.1_title": "Keep Passport Copies",
    "rules.1_desc": "Always carry digital and physical copies of your passport and visa documents.",
    "rules.2_title": "Share Your Itinerary",
    "rules.2_desc": "Tell someone you trust your travel plan, hotel details, and daily schedule.",
    "rules.3_title": "Use Official Transport",
    "rules.3_desc": "Only use licenced taxis, OLA/UBERS, or book tickets via IRCTC or through any registered apps.",
    "rules.4_title": "Save Numbers Offline or on device",
    "rules.4_desc": "Store emergency contacts 112, 108, Hotel, Family & Tourist Police offline on your device.",
    "rules.5_title": "Register Every City",
    "rules.5_desc": "This portal will keep a track of your location to keep you safe from high risk area.",
    "modal.title": "Report an Incident",
    "modal.name": "Your Name as per passport",
    "modal.incident_type": "Incident Type",
    "modal.location": "Location",
    "modal.description": "Description",
    "modal.submit": "Submit Report",
    "modal.cancel": "Cancel",
    "modal.submitted": "Report Submitted!",
    "footer.mission": "Dedicated to making India the safest and most welcoming destination for every traveller.",
    "footer.links_title": "Quick Links",
    "footer.home": "Home",
    "footer.safety": "Safety Guide",
    "footer.emergency": "Emergency Contacts",
    "footer.about": "About",
    "footer.ministry": "Ministry of Tourism, Government of India",
    "footer.rights": "2024 Trust Tour. All rights reserved.",
  },
  ru: {
    // Russian translation
    "header.tagline": "Инициатива Министерства туризма Индии",
    "header.lang_en": "EN",
    "header.lang_hi": "हिंदी",
    "header.tourist_login": "Вход для туристов",
    "hero.title": "Ваша безопасность - наш приоритет",
    "hero.subtitle": "Добро пожаловать в Индию! Мы стремимся сделать ваше путешествие безопасным.",
    "hero.badge1": "Шифрование данных",
    "hero.badge2": "Поддержка 24/7",
    "hero.badge3": "Официальный доступ",
    "traveler.heading": "Регистрация путешествия",
    "traveler.subheading": "Зарегистрируйтесь здесь",
    "traveler.name": "Полное имя",
    "traveler.passport": "Номер паспорта",
    "traveler.phone": "Номер телефона",
    "traveler.city": "Текущий город",
    "traveler.nationality": "Национальность",
    "traveler.name_placeholder": "напр. Иван Иванов",
    "traveler.passport_placeholder": "напр. A12345678",
    "traveler.phone_placeholder": "+91 9876878595",
    "traveler.city_placeholder": "напр. Нью-Дели",
    "traveler.nationality_placeholder": "напр. Россия",
    "traveler.submit": "Отправить",
    "traveler.submitted": "Регистрация завершена!",
    "authority.badge": "Departmental Access Only",
    "authority.heading": "Police / Authority Access",
    "authority.subheading": "Secure portal for verified government officials only.",
    "authority.officer_id": "Officer ID",
    "authority.password": "Password",
    "authority.officer_id_placeholder": "Enter your ID",
    "authority.password_placeholder": "Enter your password",
    "authority.login": "Secure Login",
    "authority.note": "Unauthorized access is a punishable offence.",
    "safety.section_title": "Your Safety Companion along your trip",
    "safety.section_sub": "Stay Safe in India With Us",
    "safety.emergency_title": "National Emergency",
    "safety.emergency_num": "112",
    "safety.emergency_desc": "Dial 112 for any help police, fire, or ambulance available 24/7 across India.",
    "safety.medical_title": "Medical Help",
    "safety.medical_num": "108",
    "safety.medical_desc": "108 Ambulance Services free emergency medical response.",
    "safety.police_title": "Tourist Police",
    "safety.police_num": "1800-111-363",
    "safety.police_desc": "Toll-free helpline dedicated to tourist assistance and safety.",
    "safety.rights_title": "Know Your Rights",
    "safety.rights_desc": "As a tourist you have the right to police assistance, fair pricing, and emergency access to all goods.",
    "safety.tips_title": "Safe Travel Tips",
    "safety.tips_desc": "Follow the 5 Golden Rules for a safe and comfortable journey across India.",
    "safety.report_title": "Report an Incident",
    "safety.report_desc": "Experienced a problem? Report it instantly and get help from authorities.",
    "safety.report_btn": "Report Now",
    "rules.title": "5 Golden Rules",
    "rules.subtitle": "for a Safe Journey in India",
    "rules.1_title": "Keep Passport Copies",
    "rules.1_desc": "Always carry digital and physical copies of your passport and visa documents.",
    "rules.2_title": "Share Your Itinerary",
    "rules.2_desc": "Tell someone you trust your travel plan, hotel details, and daily schedule.",
    "rules.3_title": "Use Official Transport",
    "rules.3_desc": "Only use licenced taxis, OLA/UBERS, or book tickets via IRCTC or through any registered apps.",
    "rules.4_title": "Save Numbers Offline or on device",
    "rules.4_desc": "Store emergency contacts 112, 108, Hotel, Family & Tourist Police offline on your device.",
    "rules.5_title": "Register Every City",
    "rules.5_desc": "This portal will keep a track of your location to keep you safe from high risk area.",
    "modal.title": "Report an Incident",
    "modal.name": "Your Name as per passport",
    "modal.incident_type": "Incident Type",
    "modal.location": "Location",
    "modal.description": "Description",
    "modal.submit": "Submit Report",
    "modal.cancel": "Cancel",
    "modal.submitted": "Report Submitted!",
    "footer.mission": "Dedicated to making India the safest and most welcoming destination for every traveller.",
    "footer.links_title": "Quick Links",
    "footer.home": "Home",
    "footer.safety": "Safety Guide",
    "footer.emergency": "Emergency Contacts",
    "footer.about": "About",
    "footer.ministry": "Ministry of Tourism, Government of India",
    "footer.rights": "2024 Trust Tour. All rights reserved.",
  },
  es: {
    // Spanish translation
    "header.tagline": "Impulsado por la Iniciativa de Turismo del Gobierno de la India",
    "header.lang_en": "EN",
    "header.lang_hi": "हिंदी",
    "header.tourist_login": "Inicio de Sesión para Turistas",
    "hero.title": "Su Seguridad es Nuestra Prioridad",
    "hero.subtitle": "¡Bienvenido a la India! Estamos comprometidos a hacer de su viaje una experiencia segura y memorable.",
    "hero.badge1": "Detalles Encriptados",
    "hero.badge2": "Soporte 24/7",
    "hero.badge3": "Acceso Oficial",
    "traveler.heading": "Registre Su Viaje",
    "traveler.subheading": "Cuéntenos sobre su viaje",
    "traveler.name": "Nombre Completo",
    "traveler.passport": "Número de Pasaporte",
    "traveler.phone": "Número de Teléfono",
    "traveler.city": "Ciudad Actual",
    "traveler.nationality": "Nacionalidad",
    "traveler.name_placeholder": "ej. John Smith",
    "traveler.passport_placeholder": "ej. A12345678",
    "traveler.phone_placeholder": "+91 9876878595",
    "traveler.city_placeholder": "ej. Nueva Delhi",
    "traveler.nationality_placeholder": "ej. España",
    "traveler.submit": "Enviar",
    "traveler.submitted": "¡Registro Enviado!",
    "authority.badge": "Departmental Access Only",
    "authority.heading": "Police / Authority Access",
    "authority.subheading": "Secure portal for verified government officials only.",
    "authority.officer_id": "Officer ID",
    "authority.password": "Password",
    "authority.officer_id_placeholder": "Enter your ID",
    "authority.password_placeholder": "Enter your password",
    "authority.login": "Secure Login",
    "authority.note": "Unauthorized access is a punishable offence.",
    "safety.section_title": "Your Safety Companion along your trip",
    "safety.section_sub": "Stay Safe in India With Us",
    "safety.emergency_title": "National Emergency",
    "safety.emergency_num": "112",
    "safety.emergency_desc": "Dial 112 for any help police, fire, or ambulance available 24/7 across India.",
    "safety.medical_title": "Medical Help",
    "safety.medical_num": "108",
    "safety.medical_desc": "108 Ambulance Services free emergency medical response.",
    "safety.police_title": "Tourist Police",
    "safety.police_num": "1800-111-363",
    "safety.police_desc": "Toll-free helpline dedicated to tourist assistance and safety.",
    "safety.rights_title": "Know Your Rights",
    "safety.rights_desc": "As a tourist you have the right to police assistance, fair pricing, and emergency access to all goods.",
    "safety.tips_title": "Safe Travel Tips",
    "safety.tips_desc": "Follow the 5 Golden Rules for a safe and comfortable journey across India.",
    "safety.report_title": "Report an Incident",
    "safety.report_desc": "Experienced a problem? Report it instantly and get help from authorities.",
    "safety.report_btn": "Report Now",
    "rules.title": "5 Golden Rules",
    "rules.subtitle": "for a Safe Journey in India",
    "rules.1_title": "Keep Passport Copies",
    "rules.1_desc": "Always carry digital and physical copies of your passport and visa documents.",
    "rules.2_title": "Share Your Itinerary",
    "rules.2_desc": "Tell someone you trust your travel plan, hotel details, and daily schedule.",
    "rules.3_title": "Use Official Transport",
    "rules.3_desc": "Only use licenced taxis, OLA/UBERS, or book tickets via IRCTC or through any registered apps.",
    "rules.4_title": "Save Numbers Offline or on device",
    "rules.4_desc": "Store emergency contacts 112, 108, Hotel, Family & Tourist Police offline on your device.",
    "rules.5_title": "Register Every City",
    "rules.5_desc": "This portal will keep a track of your location to keep you safe from high risk area.",
    "modal.title": "Report an Incident",
    "modal.name": "Your Name as per passport",
    "modal.incident_type": "Incident Type",
    "modal.location": "Location",
    "modal.description": "Description",
    "modal.submit": "Submit Report",
    "modal.cancel": "Cancel",
    "modal.submitted": "Report Submitted!",
    "footer.mission": "Dedicated to making India the safest and most welcoming destination for every traveller.",
    "footer.links_title": "Quick Links",
    "footer.home": "Home",
    "footer.safety": "Safety Guide",
    "footer.emergency": "Emergency Contacts",
    "footer.about": "About",
    "footer.ministry": "Ministry of Tourism, Government of India",
    "footer.rights": "2024 Trust Tour. All rights reserved.",
  },
  de: {
    // German translation
    "header.tagline": "Unterstützt durch die Tourismusinitiative der indischen Regierung",
    "header.lang_en": "EN",
    "header.lang_hi": "हिंदी",
    "header.tourist_login": "Touristen-Login",
    "hero.title": "Ihre Sicherheit ist unsere Priorität",
    "hero.subtitle": "Willkommen in Indien! Wir setzen uns dafür ein, Ihre Reise sicher und unvergesslich zu machen.",
    "hero.badge1": "Verschlüsselte Details",
    "hero.badge2": "24/7 Support",
    "hero.badge3": "Offizieller Zugang",
    "traveler.heading": "Registrieren Sie Ihre Reise",
    "traveler.subheading": "Teilen Sie uns Ihre Reisedetails mit",
    "traveler.name": "Vollständiger Name",
    "traveler.passport": "Passnummer",
    "traveler.phone": "Telefonnummer",
    "traveler.city": "Aktuelle Stadt",
    "traveler.nationality": "Nationalität",
    "traveler.name_placeholder": "z. B. Max Mustermann",
    "traveler.passport_placeholder": "z. B. A12345678",
    "traveler.phone_placeholder": "+91 9876878595",
    "traveler.city_placeholder": "z. B. Neu-Delhi",
    "traveler.nationality_placeholder": "z. B. Deutschland",
    "traveler.submit": "Einreichen",
    "traveler.submitted": "Registrierung eingereicht!",
    "authority.badge": "Departmental Access Only",
    "authority.heading": "Police / Authority Access",
    "authority.subheading": "Secure portal for verified government officials only.",
    "authority.officer_id": "Officer ID",
    "authority.password": "Password",
    "authority.officer_id_placeholder": "Enter your ID",
    "authority.password_placeholder": "Enter your password",
    "authority.login": "Secure Login",
    "authority.note": "Unauthorized access is a punishable offence.",
    "safety.section_title": "Your Safety Companion along your trip",
    "safety.section_sub": "Stay Safe in India With Us",
    "safety.emergency_title": "National Emergency",
    "safety.emergency_num": "112",
    "safety.emergency_desc": "Dial 112 for any help police, fire, or ambulance available 24/7 across India.",
    "safety.medical_title": "Medical Help",
    "safety.medical_num": "108",
    "safety.medical_desc": "108 Ambulance Services free emergency medical response.",
    "safety.police_title": "Tourist Police",
    "safety.police_num": "1800-111-363",
    "safety.police_desc": "Toll-free helpline dedicated to tourist assistance and safety.",
    "safety.rights_title": "Know Your Rights",
    "safety.rights_desc": "As a tourist you have the right to police assistance, fair pricing, and emergency access to all goods.",
    "safety.tips_title": "Safe Travel Tips",
    "safety.tips_desc": "Follow the 5 Golden Rules for a safe and comfortable journey across India.",
    "safety.report_title": "Report an Incident",
    "safety.report_desc": "Experienced a problem? Report it instantly and get help from authorities.",
    "safety.report_btn": "Report Now",
    "rules.title": "5 Golden Rules",
    "rules.subtitle": "for a Safe Journey in India",
    "rules.1_title": "Keep Passport Copies",
    "rules.1_desc": "Always carry digital and physical copies of your passport and visa documents.",
    "rules.2_title": "Share Your Itinerary",
    "rules.2_desc": "Tell someone you trust your travel plan, hotel details, and daily schedule.",
    "rules.3_title": "Use Official Transport",
    "rules.3_desc": "Only use licenced taxis, OLA/UBERS, or book tickets via IRCTC or through any registered apps.",
    "rules.4_title": "Save Numbers Offline or on device",
    "rules.4_desc": "Store emergency contacts 112, 108, Hotel, Family & Tourist Police offline on your device.",
    "rules.5_title": "Register Every City",
    "rules.5_desc": "This portal will keep a track of your location to keep you safe from high risk area.",
    "modal.title": "Report an Incident",
    "modal.name": "Your Name as per passport",
    "modal.incident_type": "Incident Type",
    "modal.location": "Location",
    "modal.description": "Description",
    "modal.submit": "Submit Report",
    "modal.cancel": "Cancel",
    "modal.submitted": "Report Submitted!",
    "footer.mission": "Dedicated to making India the safest and most welcoming destination for every traveller.",
    "footer.links_title": "Quick Links",
    "footer.home": "Home",
    "footer.safety": "Safety Guide",
    "footer.emergency": "Emergency Contacts",
    "footer.about": "About",
    "footer.ministry": "Ministry of Tourism, Government of India",
    "footer.rights": "2024 Trust Tour. All rights reserved.",
  },
  ar: {
    // Arabic translation
    "header.tagline": "بدعم من مبادرة السياحة التابعة لحكومة الهند",
    "header.lang_en": "EN",
    "header.lang_hi": "हिंदी",
    "header.tourist_login": "تسجيل دخول السائح",
    "hero.title": "سلامتك هي أولويتنا",
    "hero.subtitle": "مرحباً بك في الهند! نحن ملتزمون بجعل رحلتك آمنة ولا تُنسى.",
    "hero.badge1": "تفاصيل مشفرة",
    "hero.badge2": "دعم على مدار الساعة",
    "hero.badge3": "وصول رسمي",
    "traveler.heading": "سجل رحلتك",
    "traveler.subheading": "أخبرنا عن مسار رحلتك",
    "traveler.name": "الاسم الكامل",
    "traveler.passport": "رقم الجواز",
    "traveler.phone": "رقم الهاتف",
    "traveler.city": "المدينة الحالية",
    "traveler.nationality": "الجنسية",
    "traveler.name_placeholder": "مثل: جون سميث",
    "traveler.passport_placeholder": "مثل: A12345678",
    "traveler.phone_placeholder": "+91 9876878595",
    "traveler.city_placeholder": "مثل: نيودلهي",
    "traveler.nationality_placeholder": "مثل: المملكة العربية السعودية",
    "traveler.submit": "إرسال التسجيل",
    "traveler.submitted": "تم إرسال التسجيل!",
    "authority.badge": "وصول الأقسام فقط",
    "authority.heading": "وصول الشرطة / السلطة",
    "authority.subheading": "بوابة آمنة للمسؤولين الحكوميين المعتمدين فقط.",
    "authority.officer_id": "رقم الضابط",
    "authority.password": "كلمة المرور",
    "authority.officer_id_placeholder": "أدخل معرفك",
    "authority.password_placeholder": "أدخل كلمة المرور الخاصة بك",
    "authority.login": "تسجيل دخول آمن",
    "authority.note": "الوصول غير المصرح به جريمة يعاقب عليها القانون.",
    "safety.section_title": "رفيق سلامتك أثناء رحلتك",
    "safety.section_sub": "ابق آمناً في الهند معنا",
    "safety.emergency_title": "الطوارئ الوطنية",
    "safety.emergency_num": "112",
    "safety.emergency_desc": "اتصل بالرقم 112 لأي مساعدة، متوفر على مدار الساعة في جميع أنحاء الهند.",
    "safety.medical_title": "مساعدة طبية",
    "safety.medical_num": "108",
    "safety.medical_desc": "خدمات الإسعاف 108 استجابة طبية طارئة مجانية.",
    "safety.police_title": "الشرطة السياحية",
    "safety.police_num": "1800-111-363",
    "safety.police_desc": "خط المساعدة المجاني المخصص لمساعدة السياح وسلامتهم.",
    "safety.rights_title": "اعرف حقوقك",
    "safety.rights_desc": "كسائح، لديك الحق في مساعدة الشرطة، أسعار عادلة، ووصول الطوارئ.",
    "safety.tips_title": "نصائح السفر الآمن",
    "safety.tips_desc": "اتبع القواعد الذهبية الخمس لرحلة آمنة ومريحة في جميع أنحاء الهند.",
    "safety.report_title": "الإبلاغ عن حادث",
    "safety.report_desc": "واجهت مشكلة؟ أبلغ عنها فوراً واحصل على مساعدة من السلطات.",
    "safety.report_btn": "أبلغ الآن",
    "rules.title": "5 قواعد ذهبية",
    "rules.subtitle": "لرحلة آمنة في الهند",
    "rules.1_title": "احتفظ بنسخ الجواز",
    "rules.1_desc": "احمل دائماً نسخاً رقمية ومادية من جواز سفرك وتأشيرتك.",
    "rules.2_title": "شارك مسار رحلتك",
    "rules.2_desc": "أخبر شخصاً تثق به بخطة سفرك، تفاصيل الفندق، والجدول اليومي.",
    "rules.3_title": "استخدم وسائل النقل الرسمية",
    "rules.3_desc": "استخدم فقط سيارات الأجرة المرخصة أو احجز التذاكر عبر التطبيقات المسجلة.",
    "rules.4_title": "احفظ الأرقام محلياً",
    "rules.4_desc": "خزن أرقام الطوارئ محلياً على جهازك.",
    "rules.5_title": "سجل كل مدينة",
    "rules.5_desc": "ستقوم هذه البوابة بتتبع موقعك لإبقائك آمناً.",
    "modal.title": "الإبلاغ عن حادث",
    "modal.name": "اسمك كما في الجواز",
    "modal.incident_type": "نوع الحادث",
    "modal.location": "الموقع",
    "modal.description": "الوصف",
    "modal.submit": "إرسال التقرير",
    "modal.cancel": "إلغاء",
    "modal.submitted": "تم إرسال التقرير!",
    "footer.mission": "مكرسين لجعل الهند الوجهة الأكثر أماناً للجميع.",
    "footer.links_title": "روابط سريعة",
    "footer.home": "الرئيسية",
    "footer.safety": "دليل السلامة",
    "footer.emergency": "جهات اتصال الطوارئ",
    "footer.about": "حول",
    "footer.ministry": "وزارة السياحة، حكومة الهند",
    "footer.rights": "2024 ترست تور. جميع الحقوق محفوظة.",
  },
  zh: {
    // Chinese translation
    "header.tagline": "由印度政府旅游局倡议提供支持",
    "header.lang_en": "EN",
    "header.lang_hi": "हिंदी",
    "header.tourist_login": "游客登录",
    "hero.title": "您的安全是我们的首要任务",
    "hero.subtitle": "欢迎来到印度！我们致力于让您的旅程安全而难忘。",
    "hero.badge1": "加密详情",
    "hero.badge2": "24/7 全天候支持",
    "hero.badge3": "官方权威访问",
    "traveler.heading": "登记您的旅行",
    "traveler.subheading": "请填写并告诉我们您的行程",
    "traveler.name": "全名",
    "traveler.passport": "护照号码",
    "traveler.phone": "电话号码",
    "traveler.city": "当前城市",
    "traveler.nationality": "国籍",
    "traveler.name_placeholder": "例如：John Smith",
    "traveler.passport_placeholder": "例如：A12345678",
    "traveler.phone_placeholder": "+91 9876878595",
    "traveler.city_placeholder": "例如：新德里",
    "traveler.nationality_placeholder": "例如：中国",
    "traveler.submit": "提交登记",
    "traveler.submitted": "登记已提交！",
    "authority.badge": "仅限部门访问",
    "authority.heading": "警察/监管机构入口",
    "authority.subheading": "仅面向经过验证的政府官员的安全门户。",
    "authority.officer_id": "警官编号",
    "authority.password": "密码",
    "authority.officer_id_placeholder": "输入您的编号",
    "authority.password_placeholder": "输入您的密码",
    "authority.login": "安全登录",
    "authority.note": "未经授权的访问将被起诉。",
    "safety.section_title": "旅途中的安全伴侣",
    "safety.section_sub": "与我们一起在印度安全旅行",
    "safety.emergency_title": "国家紧急救援",
    "safety.emergency_num": "112",
    "safety.emergency_desc": "拨打112寻求警察、消防或救护车的任何帮助，印度全境24/7可用。",
    "safety.medical_title": "医疗求助",
    "safety.medical_num": "108",
    "safety.medical_desc": "108 救护车服务提供免费的紧急医疗响应。",
    "safety.police_title": "旅游警察",
    "safety.police_num": "1800-111-363",
    "safety.police_desc": "专门为游客提供援助和安全保障的免费求助热线。",
    "safety.rights_title": "了解您的权利",
    "safety.rights_desc": "作为游客，您有权获得警察协助、公平定价和紧急获取所有物品的权利。",
    "safety.tips_title": "安全出行建议",
    "safety.tips_desc": "遵循5项黄金法则，确保在印度各地的旅程安全舒适。",
    "safety.report_title": "报告事件",
    "safety.report_desc": "遇到问题了？立即报告并获得相关部门的帮助。",
    "safety.report_btn": "立即报告",
    "rules.title": "5项黄金法则",
    "rules.subtitle": "让印度之旅更安全",
    "rules.1_title": "保存护照复印件",
    "rules.1_desc": "务必随身携带护照和签证文件的数字及纸质复印件。",
    "rules.2_title": "分享您的行程",
    "rules.2_desc": "将旅行计划、酒店详细信息和每日日程告知您信任的人。",
    "rules.3_title": "使用官方交通工具",
    "rules.3_desc": "仅使用有执照的出租车、OLA/UBER，或通过通过注册的应用程序订票。",
    "rules.4_title": "离线保存号码",
    "rules.4_desc": "在您的设备上离线存储112、108、酒店、家人和旅游警察等紧急联系方式。",
    "rules.5_title": "登记所在城市",
    "rules.5_desc": "该门户网站将追踪您的位置，帮助您避开高风险区域。",
    "modal.title": "报告事件",
    "modal.name": "您的名字（与护照一致）",
    "modal.incident_type": "事件类型",
    "modal.location": "发生地点",
    "modal.description": "事件描述",
    "modal.submit": "提交报告",
    "modal.cancel": "取消",
    "modal.submitted": "报告已提交！",
    "footer.mission": "旨在使印度对每位旅行者而言成为最安全且热情的目的地。",
    "footer.links_title": "快捷链接",
    "footer.home": "首页",
    "footer.safety": "安全指南",
    "footer.emergency": "紧急联系",
    "footer.about": "关于我们",
    "footer.ministry": "印度政府旅游部",
    "footer.rights": "2024 Trust Tour。保留所有权利。",
  },
  it: {
    // Italian translation
    "header.tagline": "Realizzato dall'Iniziativa Turistica del Governo dell'India",
    "header.lang_en": "EN",
    "header.lang_hi": "हिंदी",
    "header.tourist_login": "Accesso Turista",
    "hero.title": "La Tua Sicurezza è la Nostra Priorità",
    "hero.subtitle": "Benvenuto in India! Ci impegniamo a rendere il tuo viaggio sicuro e memorabile.",
    "hero.badge1": "Dettagli Crittografati",
    "hero.badge2": "Supporto 24/7",
    "hero.badge3": "Accesso Ufficiale",
    "traveler.heading": "Registra il Tuo Viaggio",
    "traveler.subheading": "Parlaci del tuo itinerario",
    "traveler.name": "Nome Completo",
    "traveler.passport": "Numero di Passaporto",
    "traveler.phone": "Numero di Telefono",
    "traveler.city": "Città Attuale",
    "traveler.nationality": "Nazionalità",
    "traveler.name_placeholder": "es. John Smith",
    "traveler.passport_placeholder": "es. A12345678",
    "traveler.phone_placeholder": "+91 9876878595",
    "traveler.city_placeholder": "es. Nuova Delhi",
    "traveler.nationality_placeholder": "es. Italia",
    "traveler.submit": "Invia",
    "traveler.submitted": "Registrazione Inviata!",
    "authority.badge": "Accesso Dipartimentale Solo",
    "authority.heading": "Accesso Polizia / Autorità",
    "authority.subheading": "Portale sicuro solo per funzionari governativi verificati.",
    "authority.officer_id": "ID Ufficiale",
    "authority.password": "Password",
    "authority.officer_id_placeholder": "Inserisci il tuo ID",
    "authority.password_placeholder": "Inserisci la tua password",
    "authority.login": "Accesso Sicuro",
    "authority.note": "L'accesso non autorizzato è un reato punibile.",
    "safety.section_title": "Il tuo Compagno di Sicurezza durante il tuo viaggio",
    "safety.section_sub": "Rimani Al Sicuro in India con Noi",
    "safety.emergency_title": "Emergenza Nazionale",
    "safety.emergency_num": "112",
    "safety.emergency_desc": "Chiama il 112 per qualsiasi aiuto dalla polizia, vigili del fuoco o ambulanza disponibile 24/7 in tutta l'India.",
    "safety.medical_title": "Assistenza Medica",
    "safety.medical_num": "108",
    "safety.medical_desc": "Servizi di Ambulanza 108 risposta medica di emergenza gratuita.",
    "safety.police_title": "Polizia Turistica",
    "safety.police_num": "1800-111-363",
    "safety.police_desc": "Linea di assistenza gratuita dedicata all'assistenza e alla sicurezza dei turisti.",
    "safety.rights_title": "Conosci i Tuoi Diritti",
    "safety.rights_desc": "Come turista hai diritto all'assistenza della polizia, prezzi equi e accesso di emergenza a tutti i beni.",
    "safety.tips_title": "Consigli per un Viaggio Sicuro",
    "safety.tips_desc": "Segui le 5 Regole d'Oro per un viaggio sicuro e confortevole in tutta l'India.",
    "safety.report_title": "Segnala un Incidente",
    "safety.report_desc": "Hai riscontrato un problema? Segnalalo istantaneamente e ottieni aiuto dalle autorità.",
    "safety.report_btn": "Segnala Ora",
    "rules.title": "5 Regole d'Oro",
    "rules.subtitle": "per un Viaggio Sicuro in India",
    "rules.1_title": "Conserva le Copie del Passaporto",
    "rules.1_desc": "Porta sempre con te copie digitali e fisiche del passaporto e dei documenti per il visto.",
    "rules.2_title": "Condividi il tuo Itinerario",
    "rules.2_desc": "Comunica a una persona di fiducia il tuo piano di viaggio, i dettagli dell'hotel e il programma giornaliero.",
    "rules.3_title": "Usa Trasporto Ufficiale",
    "rules.3_desc": "Usa solo taxi autorizzati, OLA/UBER o prenota i biglietti tramite IRCTC o app registrate.",
    "rules.4_title": "Salva i Numeri Offline",
    "rules.4_desc": "Salva i contatti di emergenza 112, 108, Hotel, Famiglia e Polizia Turistica offline sul tuo dispositivo.",
    "rules.5_title": "Registra Ogni Città",
    "rules.5_desc": "Questo portale terrà traccia della tua posizione per tenerti al sicuro dalle aree ad alto rischio.",
    "modal.title": "Segnala un Incidente",
    "modal.name": "Il tuo Nome come sul passaporto",
    "modal.incident_type": "Tipo di Incidente",
    "modal.location": "Luogo",
    "modal.description": "Descrizione",
    "modal.submit": "Invia Segnalazione",
    "modal.cancel": "Annulla",
    "modal.submitted": "Segnalazione Inviata!",
    "footer.mission": "Dedicato a rendere l'India la destinazione più sicura e accogliente per ogni viaggiatore.",
    "footer.links_title": "Link Rapidi",
    "footer.home": "Home",
    "footer.safety": "Guida alla Sicurezza",
    "footer.emergency": "Contatti di Emergenza",
    "footer.about": "Chi Siamo",
    "footer.ministry": "Ministero del Turismo, Governo dell'India",
    "footer.rights": "2024 Trust Tour. Tutti i diritti riservati.",
  },
};

const LanguageContext = createContext<LanguageContextType>({
  lang: "en",
  setLang: () => { },
  t: (k) => k,
});

export const LanguageProvider = ({ children }: { children: React.ReactNode }) => {
  const [lang, setLang] = useState<Language>("en");
  const t = (key: string) => translations[lang][key] ?? key;
  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLang = () => useContext(LanguageContext);

