import React, { createContext, useContext, useState } from "react";

type Language = "en" | "hi" | "ja" | "fr" | "ru";

interface LanguageContextType {
  lang: Language;
  setLang: (l: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Header
    "header.tagline": "Powered by Government of India Tourism Initiative",
    "header.lang_en": "EN",
    "header.lang_hi": "हिंदी",
    "header.tourist_login": "Tourist Login",

    // Hero
    "hero.title": "Your Safety is Our Priority",
    "hero.subtitle":
      "Welcome to India! We are committed to making your journey safe & memorable. Register your yourself and explore with confidence and safety.",
    "hero.badge1": " Encrypted Details",
    "hero.badge2": " 24/7 Support",
    "hero.badge3": " Official Authority Access",

    // Traveler Portal
    "traveler.heading": "Register Your Stay",
    "traveler.subheading":
      "Register yourself here and let us know your journey",
    "traveler.name": "Full Name",
    "traveler.passport": "Passport Number",
    "traveler.phone": "Phone Number",
    "traveler.city": "Current City",
    "traveler.nationality": "Nationality",
    "traveler.name_placeholder": "e.g. John Smith",
    "traveler.passport_placeholder": "e.g. A12345678",
    "traveler.phone_placeholder": "+91 9876878595",
    "traveler.city_placeholder": "e.g. New Delhi",
    "traveler.nationality_placeholder": "e.g. United Kingdom",
    "traveler.submit": "Submit Registration",
    "traveler.submitted": "Registration Submitted!",

    // Authority Portal
    "authority.badge": "Departmental Access Only",
    "authority.heading": "Police / Authority Access",
    "authority.subheading":
      "Secure portal for verified government officials only.",
    "authority.officer_id": "Officer ID",
    "authority.password": "Password",
    "authority.officer_id_placeholder": "Enter your ID",
    "authority.password_placeholder": "Enter your password",
    "authority.login": "Secure Login",
    "authority.note": "Unauthorized access is a punishable offence.",

    // Safety Guide
    "safety.section_title": "Your Safety Companion along your trip",
    "safety.section_sub": "Stay Safe in India With Us",
    "safety.emergency_title": "National Emergency",
    "safety.emergency_num": "112",
    "safety.emergency_desc": "Dial 112 for any help police, fire, or ambulance available 24/7 across India.",
    "safety.medical_title": "Medical Help",
    "safety.medical_num": "108",
    "safety.medical_desc": "108 Ambulance Services free emergency medical response.",
    "safety.police_title": "Tourist Police",
    "safety.police_num": "1800-111-363",
    "safety.police_desc": "Toll-free helpline dedicated to tourist assistance and safety.",
    "safety.rights_title": "Know Your Rights",
    "safety.rights_desc":
      "As a tourist you have the right to police assistance, fair pricing, and emergency access to all goods.",
    "safety.tips_title": "Safe Travel Tips",
    "safety.tips_desc": "Follow the 5 Golden Rules for a safe and comfortable journey across India.",
    "safety.report_title": "Report an Incident",
    "safety.report_desc": "Experienced a problem? Report it instantly and get help from authorities.",
    "safety.report_btn": "Report Now",

    // Golden Rules
    "rules.title": "5 Golden Rules",
    "rules.subtitle": "for a Safe Journey in India",
    "rules.1_title": "Keep Passport Copies",
    "rules.1_desc": "Always carry digital and physical copies of your passport and visa documents.",
    "rules.2_title": "Share Your Itinerary",
    "rules.2_desc": "Tell someone you trust your travel plan, hotel details, and daily schedule.",
    "rules.3_title": "Use Official Transport",
    "rules.3_desc": "Only use licenced taxis, OLA/UBERS, or book tickets via IRCTC or through any registered apps.",
    "rules.4_title": "Save Numbers Offline or on device",
    "rules.4_desc": "Store emergency contacts 112, 108, Hotel, Family & Tourist Police offline on your device.",
    "rules.5_title": "Register Every City",
    "rules.5_desc": "This portal will keep a track of your location to keep you safe from high risk area.",

    // Report Modal
    "modal.title": "Report an Incident",
    "modal.name": "Your Name as per passport",
    "modal.incident_type": "Incident Type",
    "modal.location": "Location",
    "modal.description": "Description",
    "modal.submit": "Submit Report",
    "modal.cancel": "Cancel",
    "modal.submitted": "Report Submitted!",

    // Footer
    "footer.mission": "Dedicated to making India the safest and most welcoming destination for every traveller.",
    "footer.links_title": "Quick Links",
    "footer.home": "Home",
    "footer.safety": "Safety Guide",
    "footer.emergency": "Emergency Contacts",
    "footer.about": "About",
    "footer.ministry": "Ministry of Tourism, Government of India",
    "footer.rights": "2024 Trust Tour. All rights reserved.",
  },
  hi: {
    // Header
    "header.tagline": "भारत सरकार की पर्यटन पहल द्वारा संचालित",
    "header.lang_en": "EN",
    "header.lang_hi": "हिंदी",
    "header.tourist_login": "पर्यटक लॉगिन",

    // Hero
    "hero.title": "आपकी सुरक्षा हमारी प्राथमिकता है",
    "hero.subtitle":
      "भारत में आपका स्वागत है! हम आपकी यात्रा को सुरक्षित और यादगार बनाने के लिए प्रतिबद्ध हैं। अपना पंजीकरण करें और आत्मविश्वास और सुरक्षा के साथ पर्यटन का आनंद लें।",
    "hero.badge1": " एन्क्रिप्टेड विवरण",
    "hero.badge2": " 24/7 सहायता",
    "hero.badge3": " आधिकारिक प्राधिकरण पहुँच",

    // Traveler Portal
    "traveler.heading": "अपना ठहरना पंजीकृत करें",
    "traveler.subheading":
      "यहां अपना पंजीकरण करें और हमें अपनी यात्रा के बारे में बताएं",
    "traveler.name": "पूरा नाम",
    "traveler.passport": "पासपोर्ट नंबर",
    "traveler.phone": "फ़ोन नंबर",
    "traveler.city": "वर्तमान शहर",
    "traveler.nationality": "राष्ट्रीयता",
    "traveler.name_placeholder": "उदा. जॉन स्मिथ",
    "traveler.passport_placeholder": "उदा. A12345678",
    "traveler.phone_placeholder": "+91 9876878595",
    "traveler.city_placeholder": "उदा. नई दिल्ली",
    "traveler.nationality_placeholder": "उदा. यूनाइटेड किंगडम",
    "traveler.submit": "पंजीकरण जमा करें",
    "traveler.submitted": "पंजीकरण जमा कर दिया गया!",

    // Authority Portal
    "authority.badge": "केवल विभागीय पहुंच",
    "authority.heading": "पुलिस / प्राधिकरण पहुंच",
    "authority.subheading":
      "केवल सत्यापित सरकारी अधिकारियों के लिए सुरक्षित पोर्टल।",
    "authority.officer_id": "अधिकारी आईडी",
    "authority.password": "पासवर्ड",
    "authority.officer_id_placeholder": "अपनी आईडी दर्ज करें",
    "authority.password_placeholder": "अपना पासवर्ड दर्ज करें",
    "authority.login": "सुरक्षित लॉगिन",
    "authority.note": "अनाधिकृत पहुंच एक दंडनीय अपराध है।",

    // Safety Guide
    "safety.section_title": "आपकी यात्रा के दौरान आपका सुरक्षा साथी",
    "safety.section_sub": "हमारे साथ भारत में सुरक्षित रहें",
    "safety.emergency_title": "राष्ट्रीय आपातकाल",
    "safety.emergency_num": "112",
    "safety.emergency_desc": "पुलिस, फायर, या एम्बुलेंस की किसी भी सहायता के लिए 112 डायल करें, जो पूरे भारत में 24/7 उपलब्ध है।",
    "safety.medical_title": "चिकित्सा सहायता",
    "safety.medical_num": "108",
    "safety.medical_desc": "108 एम्बुलेंस सेवाएं निःशुल्क आपातकालीन चिकित्सा प्रतिक्रिया।",
    "safety.police_title": "पर्यटक पुलिस",
    "safety.police_num": "1800-111-363",
    "safety.police_desc": "पर्यटक सहायता और सुरक्षा को समर्पित टोल-फ्री हेल्पलाइन।",
    "safety.rights_title": "अपने अधिकार जानें",
    "safety.rights_desc":
      "एक पर्यटक के रूप में आपको पुलिस सहायता, उचित मूल्य निर्धारण और सभी वस्तुओं तक आपातकालीन पहुंच का अधिकार है।",
    "safety.tips_title": "सुरक्षित यात्रा युक्तियाँ",
    "safety.tips_desc": "भारत भर में सुरक्षित और आरामदायक यात्रा के लिए 5 सुनहरे नियमों का पालन करें।",
    "safety.report_title": "किसी घटना की रिपोर्ट करें",
    "safety.report_desc": "कोई समस्या आई? तुरंत इसकी रिपोर्ट करें और अधिकारियों से मदद पाएं।",
    "safety.report_btn": "अभी रिपोर्ट करें",

    // Golden Rules
    "rules.title": "5 सुनहरे नियम",
    "rules.subtitle": "भारत में सुरक्षित यात्रा के लिए",
    "rules.1_title": "पासपोर्ट की प्रतियां रखें",
    "rules.1_desc": "हमेशा अपने पासपोर्ट और वीज़ा दस्तावेजों की डिजिटल और भौतिक प्रतियां साथ रखें।",
    "rules.2_title": "अपनी यात्रा कार्यक्रम साझा करें",
    "rules.2_desc": "जिस पर आप भरोसा करते हैं, उसे अपनी यात्रा योजना, होटल का विवरण और दैनिक कार्यक्रम बताएं।",
    "rules.3_title": "आधिकारिक परिवहन का उपयोग करें",
    "rules.3_desc": "केवल लाइसेंस प्राप्त टैक्सियों, ओला/उबर का उपयोग करें, या आईआरसीटीसी या किसी भी पंजीकृत ऐप के माध्यम से टिकट बुक करें।",
    "rules.4_title": "नंबर ऑफ़लाइन या डिवाइस पर सहेजें",
    "rules.4_desc": "आपातकालीन संपर्क 112, 108, होटल, परिवार और पर्यटक पुलिस को अपने डिवाइस पर ऑफ़लाइन सहेजें।",
    "rules.5_title": "हर शहर को पंजीकृत करें",
    "rules.5_desc": "यह पोर्टल आपको उच्च जोखिम वाले क्षेत्र से सुरक्षित रखने के लिए आपके स्थान का ट्रैक रखेगा।",

    // Report Modal
    "modal.title": "किसी घटना की रिपोर्ट करें",
    "modal.name": "पासपोर्ट के अनुसार आपका नाम",
    "modal.incident_type": "घटना का प्रकार",
    "modal.location": "स्थान",
    "modal.description": "विवरण",
    "modal.submit": "रिपोर्ट जमा करें",
    "modal.cancel": "रद्द करें",
    "modal.submitted": "रिपोर्ट जमा हो गई!",

    // Footer
    "footer.mission": "भारत को प्रत्येक यात्री के लिए सबसे सुरक्षित और सबसे स्वागत योग्य गंतव्य बनाने के लिए समर्पित।",
    "footer.links_title": "त्वरित लिंक",
    "footer.home": "होम",
    "footer.safety": "सुरक्षा गाइड",
    "footer.emergency": "आपातकालीन संपर्क",
    "footer.about": "हमारे बारे में",
    "footer.ministry": "पर्यटन मंत्रालय, भारत सरकार",
    "footer.rights": "2024 ट्रस्ट टूर। सर्वाधिकार सुरक्षित।",
  },
  ja: {
    // Japanese translations (Mock/English fallback for brevity)
    "header.tagline": "インド政府観光局イニシアチブ提供",
    "header.lang_en": "EN",
    "header.lang_hi": "हिंदी",
    "header.tourist_login": "旅行者ログイン",
    "hero.title": "お客様の安全を第一に考えています",
    "hero.subtitle": "インドへようこそ！安全で思い出に残るご旅行をお約束いたします。",
    "hero.badge1": "暗号化された詳細情報",
    "hero.badge2": "24時間365日のサポート",
    "hero.badge3": "公式アクセス",
    "traveler.heading": "ご滞在の登録",
    "traveler.subheading": "ご旅行についてお知らせください",
    "traveler.name": "氏名",
    "traveler.passport": "パスポート番号",
    "traveler.phone": "電話番号",
    "traveler.city": "現在の都市",
    "traveler.nationality": "国籍",
    "traveler.name_placeholder": "例: John Smith",
    "traveler.passport_placeholder": "例: A12345678",
    "traveler.phone_placeholder": "+91 9876878595",
    "traveler.city_placeholder": "例: ニューデリー",
    "traveler.nationality_placeholder": "例: イギリス",
    "traveler.submit": "登録を送信",
    "traveler.submitted": "登録が完了しました！",
    // Adding fallbacks for the rest of the object
    "authority.badge": "Departmental Access Only",
    "authority.heading": "Police / Authority Access",
    "authority.subheading": "Secure portal for verified government officials only.",
    "authority.officer_id": "Officer ID",
    "authority.password": "Password",
    "authority.officer_id_placeholder": "Enter your ID",
    "authority.password_placeholder": "Enter your password",
    "authority.login": "Secure Login",
    "authority.note": "Unauthorized access is a punishable offence.",
    "safety.section_title": "Your Safety Companion along your trip",
    "safety.section_sub": "Stay Safe in India With Us",
    "safety.emergency_title": "National Emergency",
    "safety.emergency_num": "112",
    "safety.emergency_desc": "Dial 112 for any help police, fire, or ambulance available 24/7 across India.",
    "safety.medical_title": "Medical Help",
    "safety.medical_num": "108",
    "safety.medical_desc": "108 Ambulance Services free emergency medical response.",
    "safety.police_title": "Tourist Police",
    "safety.police_num": "1800-111-363",
    "safety.police_desc": "Toll-free helpline dedicated to tourist assistance and safety.",
    "safety.rights_title": "Know Your Rights",
    "safety.rights_desc": "As a tourist you have the right to police assistance, fair pricing, and emergency access to all goods.",
    "safety.tips_title": "Safe Travel Tips",
    "safety.tips_desc": "Follow the 5 Golden Rules for a safe and comfortable journey across India.",
    "safety.report_title": "Report an Incident",
    "safety.report_desc": "Experienced a problem? Report it instantly and get help from authorities.",
    "safety.report_btn": "Report Now",
    "rules.title": "5 Golden Rules",
    "rules.subtitle": "for a Safe Journey in India",
    "rules.1_title": "Keep Passport Copies",
    "rules.1_desc": "Always carry digital and physical copies of your passport and visa documents.",
    "rules.2_title": "Share Your Itinerary",
    "rules.2_desc": "Tell someone you trust your travel plan, hotel details, and daily schedule.",
    "rules.3_title": "Use Official Transport",
    "rules.3_desc": "Only use licenced taxis, OLA/UBERS, or book tickets via IRCTC or through any registered apps.",
    "rules.4_title": "Save Numbers Offline or on device",
    "rules.4_desc": "Store emergency contacts 112, 108, Hotel, Family & Tourist Police offline on your device.",
    "rules.5_title": "Register Every City",
    "rules.5_desc": "This portal will keep a track of your location to keep you safe from high risk area.",
    "modal.title": "Report an Incident",
    "modal.name": "Your Name as per passport",
    "modal.incident_type": "Incident Type",
    "modal.location": "Location",
    "modal.description": "Description",
    "modal.submit": "Submit Report",
    "modal.cancel": "Cancel",
    "modal.submitted": "Report Submitted!",
    "footer.mission": "Dedicated to making India the safest and most welcoming destination for every traveller.",
    "footer.links_title": "Quick Links",
    "footer.home": "Home",
    "footer.safety": "Safety Guide",
    "footer.emergency": "Emergency Contacts",
    "footer.about": "About",
    "footer.ministry": "Ministry of Tourism, Government of India",
    "footer.rights": "2024 Trust Tour. All rights reserved.",
  },
  fr: {
    // French translation
    "header.tagline": "Propulsé par l'Initiative du Gouvernement Indien",
    "header.lang_en": "EN",
    "header.lang_hi": "हिंदी",
    "header.tourist_login": "Connexion Touriste",
    "hero.title": "Votre Sécurité est Notre Priorité",
    "hero.subtitle": "Bienvenue en Inde ! Nous nous engageons à rendre votre voyage sûr et mémorable.",
    "hero.badge1": "Détails Cryptés",
    "hero.badge2": "Assistance 24/7",
    "hero.badge3": "Accès Officiel",
    "traveler.heading": "Enregistrez Votre Séjour",
    "traveler.subheading": "Dites-nous votre parcours",
    "traveler.name": "Nom Complet",
    "traveler.passport": "Numéro de Passeport",
    "traveler.phone": "Numéro de Téléphone",
    "traveler.city": "Ville Actuelle",
    "traveler.nationality": "Nationalité",
    "traveler.name_placeholder": "ex. John Smith",
    "traveler.passport_placeholder": "ex. A12345678",
    "traveler.phone_placeholder": "+91 9876878595",
    "traveler.city_placeholder": "ex. New Delhi",
    "traveler.nationality_placeholder": "ex. Royaume-Uni",
    "traveler.submit": "Soumettre",
    "traveler.submitted": "Enregistrement Soumis !",
    "authority.badge": "Departmental Access Only",
    "authority.heading": "Police / Authority Access",
    "authority.subheading": "Secure portal for verified government officials only.",
    "authority.officer_id": "Officer ID",
    "authority.password": "Password",
    "authority.officer_id_placeholder": "Enter your ID",
    "authority.password_placeholder": "Enter your password",
    "authority.login": "Secure Login",
    "authority.note": "Unauthorized access is a punishable offence.",
    "safety.section_title": "Your Safety Companion along your trip",
    "safety.section_sub": "Stay Safe in India With Us",
    "safety.emergency_title": "National Emergency",
    "safety.emergency_num": "112",
    "safety.emergency_desc": "Dial 112 for any help police, fire, or ambulance available 24/7 across India.",
    "safety.medical_title": "Medical Help",
    "safety.medical_num": "108",
    "safety.medical_desc": "108 Ambulance Services free emergency medical response.",
    "safety.police_title": "Tourist Police",
    "safety.police_num": "1800-111-363",
    "safety.police_desc": "Toll-free helpline dedicated to tourist assistance and safety.",
    "safety.rights_title": "Know Your Rights",
    "safety.rights_desc": "As a tourist you have the right to police assistance, fair pricing, and emergency access to all goods.",
    "safety.tips_title": "Safe Travel Tips",
    "safety.tips_desc": "Follow the 5 Golden Rules for a safe and comfortable journey across India.",
    "safety.report_title": "Report an Incident",
    "safety.report_desc": "Experienced a problem? Report it instantly and get help from authorities.",
    "safety.report_btn": "Report Now",
    "rules.title": "5 Golden Rules",
    "rules.subtitle": "for a Safe Journey in India",
    "rules.1_title": "Keep Passport Copies",
    "rules.1_desc": "Always carry digital and physical copies of your passport and visa documents.",
    "rules.2_title": "Share Your Itinerary",
    "rules.2_desc": "Tell someone you trust your travel plan, hotel details, and daily schedule.",
    "rules.3_title": "Use Official Transport",
    "rules.3_desc": "Only use licenced taxis, OLA/UBERS, or book tickets via IRCTC or through any registered apps.",
    "rules.4_title": "Save Numbers Offline or on device",
    "rules.4_desc": "Store emergency contacts 112, 108, Hotel, Family & Tourist Police offline on your device.",
    "rules.5_title": "Register Every City",
    "rules.5_desc": "This portal will keep a track of your location to keep you safe from high risk area.",
    "modal.title": "Report an Incident",
    "modal.name": "Your Name as per passport",
    "modal.incident_type": "Incident Type",
    "modal.location": "Location",
    "modal.description": "Description",
    "modal.submit": "Submit Report",
    "modal.cancel": "Cancel",
    "modal.submitted": "Report Submitted!",
    "footer.mission": "Dedicated to making India the safest and most welcoming destination for every traveller.",
    "footer.links_title": "Quick Links",
    "footer.home": "Home",
    "footer.safety": "Safety Guide",
    "footer.emergency": "Emergency Contacts",
    "footer.about": "About",
    "footer.ministry": "Ministry of Tourism, Government of India",
    "footer.rights": "2024 Trust Tour. All rights reserved.",
  },
  ru: {
    // Russian translation
    "header.tagline": "Инициатива Министерства туризма Индии",
    "header.lang_en": "EN",
    "header.lang_hi": "हिंदी",
    "header.tourist_login": "Вход для туристов",
    "hero.title": "Ваша безопасность - наш приоритет",
    "hero.subtitle": "Добро пожаловать в Индию! Мы стремимся сделать ваше путешествие безопасным.",
    "hero.badge1": "Шифрование данных",
    "hero.badge2": "Поддержка 24/7",
    "hero.badge3": "Официальный доступ",
    "traveler.heading": "Регистрация пребывания",
    "traveler.subheading": "Зарегистрируйтесь здесь",
    "traveler.name": "Полное имя",
    "traveler.passport": "Номер паспорта",
    "traveler.phone": "Номер телефона",
    "traveler.city": "Текущий город",
    "traveler.nationality": "Национальность",
    "traveler.name_placeholder": "напр. Иван Иванов",
    "traveler.passport_placeholder": "напр. A12345678",
    "traveler.phone_placeholder": "+91 9876878595",
    "traveler.city_placeholder": "напр. Нью-Дели",
    "traveler.nationality_placeholder": "напр. Россия",
    "traveler.submit": "Отправить",
    "traveler.submitted": "Регистрация завершена!",
    "authority.badge": "Departmental Access Only",
    "authority.heading": "Police / Authority Access",
    "authority.subheading": "Secure portal for verified government officials only.",
    "authority.officer_id": "Officer ID",
    "authority.password": "Password",
    "authority.officer_id_placeholder": "Enter your ID",
    "authority.password_placeholder": "Enter your password",
    "authority.login": "Secure Login",
    "authority.note": "Unauthorized access is a punishable offence.",
    "safety.section_title": "Your Safety Companion along your trip",
    "safety.section_sub": "Stay Safe in India With Us",
    "safety.emergency_title": "National Emergency",
    "safety.emergency_num": "112",
    "safety.emergency_desc": "Dial 112 for any help police, fire, or ambulance available 24/7 across India.",
    "safety.medical_title": "Medical Help",
    "safety.medical_num": "108",
    "safety.medical_desc": "108 Ambulance Services free emergency medical response.",
    "safety.police_title": "Tourist Police",
    "safety.police_num": "1800-111-363",
    "safety.police_desc": "Toll-free helpline dedicated to tourist assistance and safety.",
    "safety.rights_title": "Know Your Rights",
    "safety.rights_desc": "As a tourist you have the right to police assistance, fair pricing, and emergency access to all goods.",
    "safety.tips_title": "Safe Travel Tips",
    "safety.tips_desc": "Follow the 5 Golden Rules for a safe and comfortable journey across India.",
    "safety.report_title": "Report an Incident",
    "safety.report_desc": "Experienced a problem? Report it instantly and get help from authorities.",
    "safety.report_btn": "Report Now",
    "rules.title": "5 Golden Rules",
    "rules.subtitle": "for a Safe Journey in India",
    "rules.1_title": "Keep Passport Copies",
    "rules.1_desc": "Always carry digital and physical copies of your passport and visa documents.",
    "rules.2_title": "Share Your Itinerary",
    "rules.2_desc": "Tell someone you trust your travel plan, hotel details, and daily schedule.",
    "rules.3_title": "Use Official Transport",
    "rules.3_desc": "Only use licenced taxis, OLA/UBERS, or book tickets via IRCTC or through any registered apps.",
    "rules.4_title": "Save Numbers Offline or on device",
    "rules.4_desc": "Store emergency contacts 112, 108, Hotel, Family & Tourist Police offline on your device.",
    "rules.5_title": "Register Every City",
    "rules.5_desc": "This portal will keep a track of your location to keep you safe from high risk area.",
    "modal.title": "Report an Incident",
    "modal.name": "Your Name as per passport",
    "modal.incident_type": "Incident Type",
    "modal.location": "Location",
    "modal.description": "Description",
    "modal.submit": "Submit Report",
    "modal.cancel": "Cancel",
    "modal.submitted": "Report Submitted!",
    "footer.mission": "Dedicated to making India the safest and most welcoming destination for every traveller.",
    "footer.links_title": "Quick Links",
    "footer.home": "Home",
    "footer.safety": "Safety Guide",
    "footer.emergency": "Emergency Contacts",
    "footer.about": "About",
    "footer.ministry": "Ministry of Tourism, Government of India",
    "footer.rights": "2024 Trust Tour. All rights reserved.",
  },
};

const LanguageContext = createContext<LanguageContextType>({
  lang: "en",
  setLang: () => { },
  t: (k) => k,
});

export const LanguageProvider = ({ children }: { children: React.ReactNode }) => {
  const [lang, setLang] = useState<Language>("en");
  const t = (key: string) => translations[lang][key] ?? key;
  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLang = () => useContext(LanguageContext);

